apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: database-statefulset
  name: database-statefulset
spec:
  serviceName: database-headless
  replicas: 1
  selector:
    matchLabels:
      app: database-statefulset
  template:
    metadata:
      labels:
        app: database-statefulset
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: database-secret
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          - name: mysql-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init
        configMap:
          name: mysql-init
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: database-headless
spec:
  selector:
    app: database-statefulset
  clusterIP: None
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/mysql-data/master   
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - worker

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS todo_app;
    USE todo_app;

    USE todo_app;

    CREATE TABLE IF NOT EXISTS todos (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      done BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS audit (
      id INT AUTO_INCREMENT PRIMARY KEY,
      event_type VARCHAR(100),
      payload JSON,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
